update test action 8

diff --git a/.github/workflows/unit_test_true.yaml b/.github/workflows/unit_test_true.yaml
--- a/.github/workflows/unit_test_true.yaml
+++ b/.github/workflows/unit_test_true.yaml
@@ -26,6 +26,11 @@ jobs:
       with:
         version: "0.5.24"
 
+    - name: Install dependencies (forced fail)
+      run: |
+        echo "Simulating failure..."
+        exit 1
+
     - name: Sync dependencies
       run: uv sync
 
